/*
  WRITE A PROGRAM THAT ACCEPT VALUES OF PI ,RADIUS AND HEIGHT THE FIND THE VOLUME OF CYLINDER USING FORMULA -> 
               V=PI*SQUARE OF RADIUS*HEIGHT

2 CONVERT THE GIVEN CENTIMETERS INTO KILOMETERS AN MILLIMETERS
*/
